name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MAIN_PHP_VERSION: '8.5'

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Setup PHP
      uses: step-security/setup-php@de840ac176c62a2558231845e09841c1b62e0bd0 # v2.37.2
      with:
        php-version: ${{ env.MAIN_PHP_VERSION }}
        tools: composer, php-cs-fixer
      env:
        fail-fast: true

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run formatter
      run: php-cs-fixer fix --diff --dry-run

    - name: Run linter
      run: vendor/bin/phpstan analyse

  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['7.4', '8.5']

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Setup PHP
      uses: step-security/setup-php@de840ac176c62a2558231845e09841c1b62e0bd0 # v2.37.2
      with:
        php-version: ${{ matrix.php-versions }}
        tools: composer
      env:
        fail-fast: true

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: vendor/bin/phpunit tests/
